#!/usr/bin/env python
#
# -*- coding: utf-8 -*-
#

import sys
import json
import argparse

import logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)
_DEB = logger.debug
_INF = logger.info
_WRN = logger.warning

import video
import adventure


def parse_commandline():
    parser = argparse.ArgumentParser()
    parser.add_argument('ADVENTURE_SCRIPT')
    return parser.parse_args()

def main(adventure_script, options):
    config = adventure_script.get('system', {})
    resolution = tuple(config.get('resolution',
                                  video.DEFAULT_RESOLUTION))
    caption = config.get('window_caption', 'ScriptAdventure player')
    
    # Init screen
    video.Screen(resolution, caption)
    # Start!
    adventure.Adventure(adventure_script).start()
        

if __name__ == '__main__':
    options = parse_commandline()
    try:
        with open(options.ADVENTURE_SCRIPT, 'r') as fd:
            try:
                adventure_script = json.load(fd)
            except ValueError:
                print 'ERROR: file "%s" is not a valid JSON file' % options.ADVENTURE_SCRIPT
                sys.exit(-1)
    except IOError:
        print 'ERROR: cannot read file "%s"' % options.ADVENTURE_SCRIPT
        sys.exit(-1)
        
    main(adventure_script, options)
